# Generated by Django 5.2.8 on 2025-11-10 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6C63FF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TestPsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField()),
                ('es_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('sugerencia', 'Sugerencia'), ('duda', 'Duda'), ('problema', 'Problema Técnico'), ('otros', 'Otros')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('categoria_recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.categoriarecurso')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='miapp.preguntatest')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_recurso', models.CharField(choices=[('video', 'Video'), ('articulo', 'Artículo'), ('texto_imagen', 'Texto con Imágenes'), ('ejercicio', 'Ejercicio Práctico')], max_length=15)),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('contenido', models.TextField(blank=True)),
                ('es_publico', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.categoriarecurso')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_total', models.IntegerField()),
                ('completado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria_recomendada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.categoriarecurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.testpsicologico')),
            ],
        ),
        migrations.AddField(
            model_name='preguntatest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='miapp.testpsicologico'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('pasante', 'Pasante de Psicología'), ('paciente', 'Paciente')], default='paciente', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
