# Generated by Django 5.2.8 on 2025-11-16 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6C63FF', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('es_activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría del Foro',
                'verbose_name_plural': 'Categorías del Foro',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HiloForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('destacado', 'Destacado')], default='abierto', max_length=10)),
                ('es_anonimo', models.BooleanField(default=False)),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('visitas', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.categoriaforo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hilo del Foro',
                'verbose_name_plural': 'Hilos del Foro',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_anonimo', models.BooleanField(default=False)),
                ('es_respuesta_oficial', models.BooleanField(default=False)),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_foro', to=settings.AUTH_USER_MODEL)),
                ('hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='miapp.hiloforo')),
            ],
            options={
                'verbose_name': 'Respuesta del Foro',
                'verbose_name_plural': 'Respuestas del Foro',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='VotoHilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.hiloforo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de Hilo',
                'verbose_name_plural': 'Votos de Hilos',
                'unique_together': {('hilo', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='VotoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.respuestaforo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de Respuesta',
                'verbose_name_plural': 'Votos de Respuestas',
                'unique_together': {('respuesta', 'usuario')},
            },
        ),
    ]
