# Generated by Django 5.2.8 on 2025-11-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_categoriaforo_hiloforo_respuestaforo_votohilo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaTestPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('texto', models.TextField()),
                ('seccion', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_contenido', models.CharField(choices=[('video', 'Video'), ('infografia', 'Infografía'), ('articulo', 'Artículo'), ('ejercicio', 'Ejercicio')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='contenido_personalizado/')),
                ('url', models.URLField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_personalizado', to=settings.AUTH_USER_MODEL)),
                ('pasante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuestaPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=200)),
                ('puntaje', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.preguntatestpersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='miapp.formulariocontacto')),
                ('respondido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaTestPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('opcion_elegida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.opcionrespuestapersonalizado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.preguntatestpersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTestPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_test', models.DateTimeField(auto_now_add=True)),
                ('puntaje_total', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
