# Generated by Django 5.2.7 on 2025-11-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_preguntatestpersonalizado_contenidopersonalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
