# Generated by Django 5.2.8 on 2025-11-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_recurso_enlace_recurso_imagen_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaforo',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='hiloforo',
            options={'ordering': ['-actualizado_en']},
        ),
        migrations.AlterModelOptions(
            name='respuestaforo',
            options={'ordering': ['creado_en']},
        ),
        migrations.AlterModelOptions(
            name='votohilo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='votorespuesta',
            options={},
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='url',
        ),
    ]
