# Generated by Django 5.2.8 on 2025-11-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_alter_categoriaforo_options_alter_hiloforo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='archivo',
        ),
    ]
