# Generated by Django 5.2.8 on 2025-11-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_remove_recurso_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaforo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría del Foro', 'verbose_name_plural': 'Categorías del Foro'},
        ),
        migrations.AlterModelOptions(
            name='hiloforo',
            options={'ordering': ['-actualizado_en'], 'verbose_name': 'Hilo del Foro', 'verbose_name_plural': 'Hilos del Foro'},
        ),
        migrations.AlterModelOptions(
            name='respuestaforo',
            options={'ordering': ['creado_en'], 'verbose_name': 'Respuesta del Foro', 'verbose_name_plural': 'Respuestas del Foro'},
        ),
        migrations.AlterModelOptions(
            name='votohilo',
            options={'verbose_name': 'Voto de Hilo', 'verbose_name_plural': 'Votos de Hilos'},
        ),
        migrations.AlterModelOptions(
            name='votorespuesta',
            options={'verbose_name': 'Voto de Respuesta', 'verbose_name_plural': 'Votos de Respuestas'},
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
